GoogleCloudPlatform/cloud-build-notifiers

smtp/main.go

We don't need to log-spam the entire Build proto when we want to send email, especially without any sort of log.V(n) on it.
I flipped the condition since it is usually better to exit early when you plan on doing less work, not more.

Reduce log spam in SMTP notifier.

---

README.md
setup.sh

This will make notifier setup much easy as it automates _most_ of the `gcloud` steps required for building, deploying, configuring, etc.

Add setup.sh and update README.

---

http/buildtest.cloudbuild.yaml
http/deploy.cloudbuild.yaml
slack/buildtest.cloudbuild.yaml
slack/deploy.cloudbuild.yaml
smtp/buildtest.cloudbuild.yaml
smtp/deploy.cloudbuild.yaml

These cb.yamls will allow us to create triggers for specific build+test and separate deploy functionality. This also allows us to take advantage of semver git tagging for version tagging our notifier images.
I decided to keep the older `cloudbuild.yamls` since we still have code/docs that reference them. With these new cb.yamls, they will eventually become obsolete and we will no longer require users to build their own notifiers.

Add trigger cb.yamls for tests and deploys.

---

http/deploy.cloudbuild.yaml
slack/deploy.cloudbuild.yaml
smtp/deploy.cloudbuild.yaml

These deploy yamls now upload images to the `us-east1-docker.pkg.dev/gcb-release/cloud-build-notifiers` in `gcb-release`. The image tagging remains the same.
After these are submitted, I will setup triggers in the `cloud-build-notifiers` GCP project to run tags.

Update deploy yamls for integration with cloud-build-notifiers AR.

---

README.md
bigquery/README.md
bigquery/bigquery.yaml
http/README.md
http/http.yaml.example
lib/notifiers/README.md
lib/notifiers/notifiers.go
lib/notifiers/notifiers_test.go
slack/README.md
slack/slack.yaml.example
smtp/README.md
smtp/main_test.go
smtp/smtp.yaml.example

- validateConfig is now called in setup_check.
- Updated tests and example files to use v1 instead of v1a1.
This is something that we want to do for our GA launch.

Update config API Version to be c-b-n/v1.

---

http/deploy.cloudbuild.yaml
slack/deploy.cloudbuild.yaml
smtp/deploy.cloudbuild.yaml

This adds an image tag derived from git tag `smtp-1.2.3` to `smtp-1-latest` for example.
No other existing tags are affected.

Add major-latest tags to repository images.

---

lib/notifiers/buildtest.cloudbuild.yaml

Our other cb.yamls are triggered on changes to `lib/**` but they don't actually test it. I'll set up a PR trigger to run this specific cb.yaml.

Add cb.yaml for lib/notifiers buildtest.

---

bigquery/main.go
http/main.go
lib/notifiers/notifiers.go
slack/main.go
smtp/main.go

This uses the `%w` fmt verb to preserve underlying error information
when an error is returned. See https://blog.golang.org/go1.13-errors.
As a result, this means that GCB Notifiers requires Go >= 1.13.

Use error wrapping for returned errors.

---

slack/go.mod
slack/go.sum
slack/main.go
slack/main_test.go

Replace `nlopes/slack` to `slack-go/slack` which moved `slack-go` organization. Also upgrade to `v0.6.5`.

go.mod: replace nlopes/slack to slack-go/slack also upgrade to v0.6.5

---

lib/notifiers/Dockerfile
lib/notifiers/buildtest.cloudbuild.yaml

Just use a Dockerfile to get around the directory traversing we have to
do, like with the other directories.
I tested this in another GCP project and did a docker build locally.

Fix lib/notifiers buildtest trigger/cb.yaml.

---

setup.sh

We check for the cloud-builds pub/sub topic and create it in the case of nonexistence.
Upon any API required for the notifier ('Cloud Build API' 'Cloud Run Admin API' 'Cloud Pub/Sub API' 'Secret Manager API') not being enabled, we request the user to manually enable the API and terminate the script.
Formatted with the shell-format extension in vscode

add api check and pub/sub topic check to setup script

---

bigquery/main.go

We add a new field in the bqRow struct called LogURL that takes the build URL from the build proto and wraps it with UTM params for tracking

add UTM tracking params to logURL

---

bigquery/main.go
lib/notifiers/notifiers.go

Add a new UTM called StorageMedium, update BQ notifier to use StorageMedium for UTM tracking

Add storage utm

---

lib/notifiers/notifiers_test.go

This test case shows go to construct a CEL filter that uses the `matches` regexp helper. This was inspired by #81 .

Add test case to document CEL  filters.

---

githubissues/Dockerfile
githubissues/README.md
githubissues/buildtest.cloudbuild.yaml
githubissues/deploy.cloudbuild.yaml
githubissues/githubissues.json
githubissues/githubissues.yaml.example
githubissues/main.go
githubissues/main_test.go

b/229753500
This notifier creates an issue against the configured GitHub repo. It also uses the new template feature to allow full customisation of the notification format, including GitHub features like labels and assignees (as shown in the screenshot).

New notifier - GitHub Issues

---

setup.sh

Pub/Sub subscription and topic names cannot start with "goog"
https://cloud.google.com/pubsub/docs/admin#resource_names 
This change prepends if the notifier type is "googlechat"

prevent invalid pubsub subscription names

---

slack/main.go
slack/main_test.go

The PR provides a small fix to the slack message sent by cloud build.
The two commits have a detailed commit message so I will avoid duplication here.

slack: Add block color context

---

lib/notifiers/notifiers.go
lib/notifiers/notifiers_test.go

PR #131 added validation of config paths. Unfortunately, the validation was incorrect.
The regex from the PR: `^gs://([[\w-]+)/([^\\]+$)`
This allows the bucket name to be word characters and `-`. I.e. `config-42-example-com`.
In reality `_` and `.` is also allowed! (see https://cloud.google.com/storage/docs/buckets#naming)
Our company prefers DNS style buckets, i.e., `config.example.com`, so this change just broke our use of the build-notifiers

Fix validation of GCS bucket names

---

slack/README.md
slack/main.go
slack/main_test.go

Fixes #153 and #160 
This lets the user replace substrings in .json template variables. The most pressing need is to remove (or escape) double quotes, which breaks the template due to json not expecting unescaped double quotes. 
The Cloud Build .Build object has some properties which come with double quotes: `.Build.FailureInfo.Detail` is one such object: a typical FailureInfo object looks like:
```
failureInfo:
detail: 'Build step failure: build step 7 "gcr.io/google-appengine/exec-wrapper"
failed: step exited with non-zero status: 1'
type: USER_BUILD_STEP
```

Added a template function 'replace' to BlockKitTemplate parser

---

bigquery/Dockerfile
githubissues/Dockerfile
googlechat/Dockerfile
http/Dockerfile
lib/notifiers/Dockerfile
slack/Dockerfile
smtp/Dockerfile

When trying to build new versions of the images, these fail due to missing dynamic libs in the container:
```
Step #1: /go-app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /go-app)
Step #1: /go-app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /go-app)
```
Adding CGO_ENABLED=0 makes the go compiler produce a binary that doesn't require those libs.

Build binaries without dependency on cgo

---

go.mod
go.sum

Context: I changed my Cloud Run Job to run with the `E2_MEDIUM` machine type. Support for the `E2_MEDIUM` machine type was introduced on the version 1.12.0 of the `/go/cloudbuild` as we can [see here](https://github.com/googleapis/google-cloud-go/blob/cloudbuild/v1.14.0/cloudbuild/CHANGES.md)
This PR updates the `/go/cloudbuild` dependecy to the 1.14.0

Updating the /go/cloudbuild version to include new enum types

---

smtp/main.go
smtp/main_test.go
smtp/smtp.yaml.example

Example configuration:
```
spec:
notification:
delivery:
subject: '{{ if eq .Build.Status 3 }}✅ Build Successful ({{ .Build.Substitutions.REPO_NAME }}){{ else }}❌ Build Failure ({{ .Build.Substitutions.REPO_NAME }}){{ end }} | {{.Build.Substitutions._COMMIT_MESSAGE}}'
```

[SMTP] Customize Subject Email (by build template)

---

slack/main_test.go

As well as how to access rarer fields like from .Substitutions
This should help users in the future.  When they have the raw json from a build, they can drop it in the test themselves, and edit the template until it's running how they want.

Improve test so it's clearer how input from a pubsub build message gets converted
